export const REDMINE_AUTHEN_ERROR = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  REDMINE_NOT_LINKED: "REDMINE_NOT_LINKED",
  RE_LOGIN_FAILED: "RE_LOGIN_FAILED",
  DECRYPTION_FAILED: "DECRYPTION_FAILED",
  REDMINE_NOT_LINKED_OLD: "Please link your Redmine account.",
  MISSING_API_KEY_OLD: "Missing Config",
  REDMINE_AUTH_REQUIRED: "REDMINE_AUTH_REQUIRED",
}
